<?php

namespace Database\Seeders;

use App\Models\ComCode as Code;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('com_codes')->truncate();

        $code = Code::create(["com_cd" => "AKTIVITAS_TP_01", "code_nm" => "Ringan", "code_group" => "AKTIVITAS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "AKTIVITAS_TP_02", "code_nm" => "Sedang", "code_group" => "AKTIVITAS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "AKTIVITAS_TP_03", "code_nm" => "Berat", "code_group" => "AKTIVITAS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "APPCD_ACCCHARGE", "code_nm" => "Account - Charge Pembayaran", "code_group" => "APP_CD", "code_value" => "AC099"]);
        $code = Code::create(["com_cd" => "APPCD_APPNAME", "code_nm" => "Application Name", "code_group" => "APP_CD", "code_value" => "Sistem Informasi Manajemen RS"]);
        $code = Code::create(["com_cd" => "APPCD_DRDEFAULT", "code_nm" => "Kode Tim Dokter", "code_group" => "APP_CD", "code_value" => "TIMDOKTER"]);
        $code = Code::create(["com_cd" => "APPCD_HTTP", "code_nm" => "HTTP Server", "code_group" => "APP_CD", "code_value" => "/simrke"]);
        $code = Code::create(["com_cd" => "APPCD_INVMARGIN", "code_nm" => "Margin inventori", "code_group" => "APP_CD", "code_value" => "25"]);
        $code = Code::create(["com_cd" => "APPCD_LASTUPDATE", "code_nm" => "Last Update", "code_group" => "APP_CD", "code_value" => "1608010000.update"]);
        $code = Code::create(["com_cd" => "APPCD_LICENSE", "code_nm" => "Lisensi", "code_group" => "APP_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "APPCD_LICENSE2", "code_nm" => "Lisensi 2", "code_group" => "APP_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "APPCD_LOGOUTTIME", "code_nm" => "Logout timer (detik)", "code_group" => "APP_CD", "code_value" => "600"]);
        $code = Code::create(["com_cd" => "APPCD_PRINTER01", "code_nm" => "Default Printer Label", "code_group" => "APP_CD", "code_value" => "Foxit Reader PDF Printer"]);
        $code = Code::create(["com_cd" => "APPCD_PRINTER02", "code_nm" => "Default Printer Antrian", "code_group" => "APP_CD", "code_value" => "Foxit Reader PDF Printer"]);
        $code = Code::create(["com_cd" => "APPCD_REFFRM", "code_nm" => "No. RM Otomatis", "code_group" => "APP_CD", "code_value" => "0"]);
        $code = Code::create(["com_cd" => "APPCD_REGIONKAB", "code_nm" => "Default Kabupaten", "code_group" => "APP_CD", "code_value" => "3273"]);
        $code = Code::create(["com_cd" => "APPCD_REGIONPROV", "code_nm" => "Default Propinsi", "code_group" => "APP_CD", "code_value" => "32"]);
        $code = Code::create(["com_cd" => "APPCD_RSNAME", "code_nm" => "Hospital Name", "code_group" => "APP_CD", "code_value" => "RSKG"]);
        $code = Code::create(["com_cd" => "APPCD_SYSPASS", "code_nm" => "Network Password", "code_group" => "APP_CD", "code_value" => "simrke"]);
        $code = Code::create(["com_cd" => "APPCD_SYSSHARE", "code_nm" => "Share Folder", "code_group" => "APP_CD", "code_value" => "simrke"]);
        $code = Code::create(["com_cd" => "APPCD_SYSUSER", "code_nm" => "Network User ID", "code_group" => "APP_CD", "code_value" => "simrke"]);
        $code = Code::create(["com_cd" => "BERAT_TP_00", "code_nm" => "Normal", "code_group" => "BERAT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "BERAT_TP_10", "code_nm" => "Kurus", "code_group" => "BERAT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "BERAT_TP_20", "code_nm" => "Gemuk", "code_group" => "BERAT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "BERAT_TP_25", "code_nm" => "Obesitas", "code_group" => "BERAT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "BLOOD_TP_A", "code_nm" => "A", "code_group" => "BLOOD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "BLOOD_TP_AB", "code_nm" => "AB", "code_group" => "BLOOD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "BLOOD_TP_B", "code_nm" => "B", "code_group" => "BLOOD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "BLOOD_TP_O", "code_nm" => "O", "code_group" => "BLOOD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DAY_TP_01", "code_nm" => "Senin", "code_group" => "DAY_TP", "code_value" => "Monday"]);
        $code = Code::create(["com_cd" => "DAY_TP_02", "code_nm" => "Selasa", "code_group" => "DAY_TP", "code_value" => "Tuesday"]);
        $code = Code::create(["com_cd" => "DAY_TP_03", "code_nm" => "Rabu", "code_group" => "DAY_TP", "code_value" => "Wednesday"]);
        $code = Code::create(["com_cd" => "DAY_TP_04", "code_nm" => "Kamis", "code_group" => "DAY_TP", "code_value" => "Thursday"]);
        $code = Code::create(["com_cd" => "DAY_TP_05", "code_nm" => "Jumat", "code_group" => "DAY_TP", "code_value" => "Friday"]);
        $code = Code::create(["com_cd" => "DAY_TP_06", "code_nm" => "Sabtu", "code_group" => "DAY_TP", "code_value" => "Saturday"]);
        $code = Code::create(["com_cd" => "DAY_TP_00", "code_nm" => "Minggu", "code_group" => "DAY_TP", "code_value" => "Sunday"]);
        $code = Code::create(["com_cd" => "DOSIS_TP_01", "code_nm" => "Sendok Obat", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_02", "code_nm" => "CC", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_03", "code_nm" => "Tetes Telinga Kanan", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_04", "code_nm" => "Tetes Telinga Kiri", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_05", "code_nm" => "Tetes Mata Kanan", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_06", "code_nm" => "Tetes Mata Kiri", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_07", "code_nm" => "Tetes Hidung Kanan", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_08", "code_nm" => "Tetes Hidung Kiri", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DOSIS_TP_09", "code_nm" => "Injeksi", "code_group" => "DOSIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_01", "code_nm" => "SD", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_02", "code_nm" => "SMP", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_03", "code_nm" => "SMU", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_04", "code_nm" => "D1", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_05", "code_nm" => "D2", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_06", "code_nm" => "D3", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_07", "code_nm" => "D4", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_08", "code_nm" => "S1", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_09", "code_nm" => "S2", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_10", "code_nm" => "S3", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EXTCD_JKNAUTO", "code_nm" => "JKN - SEP Otomatis", "code_group" => "EXT_CD", "code_value" => "0"]);
        $code = Code::create(["com_cd" => "EXTCD_JKNPASS", "code_nm" => "JKN - Password RS", "code_group" => "EXT_CD", "code_value" => "2xH5EEFFC8"]);
        $code = Code::create(["com_cd" => "EXTCD_JKNRSCODE", "code_nm" => "JKN - Kode RS", "code_group" => "EXT_CD", "code_value" => "1119R001"]);
        $code = Code::create(["com_cd" => "EXTCD_JKNURL", "code_nm" => "URL Web Service JKN", "code_group" => "EXT_CD", "code_value" => "http://api.asterix.co.id/SepWebRest"]);
        $code = Code::create(["com_cd" => "EXTCD_JKNUSER", "code_nm" => "JKN - ID RS", "code_group" => "EXT_CD", "code_value" => "31990"]);
        $code = Code::create(["com_cd" => "FAMILY_TP_00", "code_nm" => "Orang Tua Kandung", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_01", "code_nm" => "Ayah", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_02", "code_nm" => "Ibu", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_03", "code_nm" => "Suami/Istri", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_04", "code_nm" => "Anak", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_05", "code_nm" => "Saudara Kandung", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_06", "code_nm" => "Kakek/Nenek", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_07", "code_nm" => "Paman/Bibi", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_08", "code_nm" => "Keluarga", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MARITAL_TP_1", "code_nm" => "Belum Menikah", "code_group" => "MARITAL_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "FAMILY_TP_20", "code_nm" => "Lain-lain", "code_group" => "FAMILY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "GENDER_TP_01", "code_nm" => "Laki-Laki", "code_group" => "GENDER_TP", "code_value" => "L"]);
        $code = Code::create(["com_cd" => "GENDER_TP_02", "code_nm" => "Perempuan", "code_group" => "GENDER_TP", "code_value" => "P"]);
        $code = Code::create(["com_cd" => "ICD_TP_00", "code_nm" => "Umum", "code_group" => "ICD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "ICD_TP_10", "code_nm" => "ICD-10", "code_group" => "ICD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "ICD-09", "code_nm" => "ICD-9", "code_group" => "TREATMENTSTD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "ID_TP_1", "code_nm" => "KTP", "code_group" => "IDENTITY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "ID_TP_2", "code_nm" => "KK", "code_group" => "IDENTITY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "ID_TP_3", "code_nm" => "SIM", "code_group" => "IDENTITY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "ID_TP_4", "code_nm" => "Paspor", "code_group" => "IDENTITY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "ID_TP_5", "code_nm" => "KITAS", "code_group" => "IDENTITY_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INSURANCE_TP_1", "code_nm" => "Peserta", "code_group" => "INSURANCE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INSURANCE_TP_2", "code_nm" => "Suami/Istri", "code_group" => "INSURANCE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INSURANCE_TP_3", "code_nm" => "Anak/Tanggungan", "code_group" => "INSURANCE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_ST_0", "code_nm" => "Close", "code_group" => "INV_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_ST_1", "code_nm" => "Input", "code_group" => "INV_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_ST_2", "code_nm" => "Approval-Open", "code_group" => "INV_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_ST_3", "code_nm" => "Approval-Close", "code_group" => "INV_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_ST_4", "code_nm" => "Proses", "code_group" => "INV_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_ST_9", "code_nm" => "Cancel", "code_group" => "INV_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_TP_1", "code_nm" => "Penerimaan", "code_group" => "INV_TRX_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_TP_2", "code_nm" => "Pengeluaran", "code_group" => "INV_TRX_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_TP_3", "code_nm" => "Penggunaan", "code_group" => "INV_TRX_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_TP_4", "code_nm" => "Transfer", "code_group" => "INV_TRX_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_TP_5", "code_nm" => "Retur", "code_group" => "INV_TRX_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_TP_6", "code_nm" => "Penyesuaian", "code_group" => "INV_TRX_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "INV_TRX_TP_9", "code_nm" => "Lain-Lain", "code_group" => "INV_TRX_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KEADAAN_TP_10", "code_nm" => "Sehat", "code_group" => "KEADAAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KEADAAN_TP_20", "code_nm" => "Sakit", "code_group" => "KEADAAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MARITAL_TP_2", "code_nm" => "Menikah", "code_group" => "MARITAL_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MARITAL_TP_3", "code_nm" => "Janda/Duda", "code_group" => "MARITAL_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICAL_TP_01", "code_nm" => "Rawat Jalan", "code_group" => "MEDICAL_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICAL_TP_02", "code_nm" => "Rawat Inap", "code_group" => "MEDICAL_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICAL_TRX_ST_0", "code_nm" => "Proses", "code_group" => "MEDICAL_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICAL_TRX_ST_1", "code_nm" => "Close", "code_group" => "MEDICAL_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICAL_TRX_ST_2", "code_nm" => "Proses Mutasi", "code_group" => "MEDICAL_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICAL_TRX_ST_3", "code_nm" => "Proses Invoice", "code_group" => "MEDICAL_TRX_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICALUNIT_TP_1", "code_nm" => "Poliklinik", "code_group" => "MEDICALUNIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICALUNIT_TP_2", "code_nm" => "Laboratorium", "code_group" => "MEDICALUNIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICALUNIT_TP_3", "code_nm" => "Radiologi", "code_group" => "MEDICALUNIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MOVE_TP_1", "code_nm" => "In", "code_group" => "MOVE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MOVE_TP_2", "code_nm" => "Out", "code_group" => "MOVE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MOVE_TP_3", "code_nm" => "Transfer", "code_group" => "MOVE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MOVE_TP_4", "code_nm" => "Konversi", "code_group" => "MOVE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MOVE_TP_5", "code_nm" => "Penyesuaian", "code_group" => "MOVE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_01", "code_nm" => "PNS", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_02", "code_nm" => "TNI", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_03", "code_nm" => "POLRI", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_04", "code_nm" => "GURU", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_05", "code_nm" => "DOSEN", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_06", "code_nm" => "PELAJAR", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_07", "code_nm" => "MAHASISWA", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_08", "code_nm" => "PETANI", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_09", "code_nm" => "NELAYAN", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_10", "code_nm" => "BURUH", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_11", "code_nm" => "SWASTA", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_12", "code_nm" => "WIRASWASTA", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_13", "code_nm" => "SEKTOR INFORMAL", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_14", "code_nm" => "IBU RUMAH TANGGA", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_98", "code_nm" => "PENSIUN", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_99", "code_nm" => "LAIN-LAIN", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OUT_TP_01", "code_nm" => "Sembuh", "code_group" => "OUT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "OUT_TP_02", "code_nm" => "Rujuk", "code_group" => "OUT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "OUT_TP_03", "code_nm" => "Pulang Paksa", "code_group" => "OUT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_01", "code_nm" => "Dokter Umum", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_02", "code_nm" => "Dokter Spesialis", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_03", "code_nm" => "Co As", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_04", "code_nm" => "Perawat", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_05", "code_nm" => "Bidan", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_06", "code_nm" => "Ahli Gizi", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_07", "code_nm" => "Fisioterapis", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_08", "code_nm" => "Petugas Laboratorium", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_09", "code_nm" => "Petugas Radiologi", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_10", "code_nm" => "Apoteker", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_11", "code_nm" => "Psikolog", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDIS_TP_12", "code_nm" => "Terapi Wicara", "code_group" => "PARAMEDIS_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDISROLE_TP_100", "code_nm" => "Dokter", "code_group" => "PARAMEDISROLE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDISROLE_TP_101", "code_nm" => "Dokter Anastesi", "code_group" => "PARAMEDISROLE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDISROLE_TP_120", "code_nm" => "Asisten Dokter", "code_group" => "PARAMEDISROLE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDISROLE_TP_200", "code_nm" => "Perawat", "code_group" => "PARAMEDISROLE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PARAMEDISROLE_TP_201", "code_nm" => "Asisten Perawat", "code_group" => "PARAMEDISROLE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PASIEN_TP_01", "code_nm" => "Umum", "code_group" => "PASIEN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PASIEN_TP_02", "code_nm" => "Jaminan", "code_group" => "PASIEN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_ST_0", "code_nm" => "Belum Bayar", "code_group" => "PAYMENT_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_ST_1", "code_nm" => "Lunas", "code_group" => "PAYMENT_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_ST_2", "code_nm" => "Tagihan (Belum Lunas)", "code_group" => "PAYMENT_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_TP_11", "code_nm" => "Tunai", "code_group" => "PAYMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_TP_12", "code_nm" => "Kartu Debit", "code_group" => "PAYMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_TP_13", "code_nm" => "Kartu Kredit", "code_group" => "PAYMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_TP_14", "code_nm" => "Transfer", "code_group" => "PAYMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_TP_15", "code_nm" => "Giro", "code_group" => "PAYMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_TP_20", "code_nm" => "Tunai + Kartu", "code_group" => "PAYMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PAYMENT_TP_21", "code_nm" => "Asuransi", "code_group" => "PAYMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PROSES_TP_OBAT", "code_nm" => "Obat", "code_group" => "PROSES_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PROSES_TP_TINDAKAN", "code_nm" => "Tindakan", "code_group" => "PROSES_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PROSES_TP_UNIT", "code_nm" => "Unit", "code_group" => "PROSES_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RACE_CD_01", "code_nm" => "MELAYU", "code_group" => "RACE_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RACE_CD_02", "code_nm" => "JAWA", "code_group" => "RACE_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RACE_CD_03", "code_nm" => "BATAK", "code_group" => "RACE_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RACE_CD_04", "code_nm" => "SUNDA", "code_group" => "RACE_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RACE_CD_99", "code_nm" => "LAIN-LAIN", "code_group" => "RACE_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_00", "code_nm" => "Sendiri", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_01", "code_nm" => "Dokter", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_02", "code_nm" => "Mantri", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_03", "code_nm" => "Bidan", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_04", "code_nm" => "Polisi", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_05", "code_nm" => "Puskesmas", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_06", "code_nm" => "Klinik", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "REFF_TP_07", "code_nm" => "Rumah Sakit", "code_group" => "REFF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RELIGION_CD_01", "code_nm" => "ISLAM", "code_group" => "RELIGION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RELIGION_CD_02", "code_nm" => "KATOLIK", "code_group" => "RELIGION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RELIGION_CD_03", "code_nm" => "PROTESTAN", "code_group" => "RELIGION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RELIGION_CD_04", "code_nm" => "HINDU", "code_group" => "RELIGION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RELIGION_CD_05", "code_nm" => "BUDHA", "code_group" => "RELIGION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RELIGION_CD_06", "code_nm" => "KONG HU CU", "code_group" => "RELIGION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RELIGION_CD_07", "code_nm" => "ALIRAN KEPERCAYAAN", "code_group" => "RELIGION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "RESEP_TP_1", "code_nm" => "Per Item", "code_group" => "RESEP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RESEP_TP_2", "code_nm" => "Racikan", "code_group" => "RESEP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RM_TP_1", "code_nm" => "Diagnosa Primer", "code_group" => "RM_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RM_TP_2", "code_nm" => "Diagnosa Sekunder", "code_group" => "RM_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RM_TP_3", "code_nm" => "Diagnosa Masuk", "code_group" => "RM_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RM_TP_4", "code_nm" => "Diagnosa Keluar", "code_group" => "RM_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "RPT_ITEMTP_01", "code_nm" => "NARKOTIKA", "code_group" => "RPT_ITEMTP", "code_value" => "NARKOTIK"]);
        $code = Code::create(["com_cd" => "RPT_ITEMTP_03", "code_nm" => "PSIKOTROPIK", "code_group" => "RPT_ITEMTP", "code_value" => "PSIKOTROPIK"]);
        $code = Code::create(["com_cd" => "RPT_ITEMTP_05", "code_nm" => "PRESEKUSOR", "code_group" => "RPT_ITEMTP", "code_value" => "PRESEKUSOR"]);
        $code = Code::create(["com_cd" => "TARIF_TP_00", "code_nm" => "Tarif General", "code_group" => "TARIF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TARIF_TP_01", "code_nm" => "Tarif Paramedis", "code_group" => "TARIF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TARIF_TP_02", "code_nm" => "Tarif Unit Medis", "code_group" => "TARIF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TARIF_TP_03", "code_nm" => "Tarif Kelas", "code_group" => "TARIF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "OUT_TP_06", "code_nm" => "Tidak Tahu", "code_group" => "OUT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TARIF_TP_04", "code_nm" => "Tarif Tindakan", "code_group" => "TARIF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TARIF_TP_05", "code_nm" => "Tarif Inventori(Obat/BHP)", "code_group" => "TARIF_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TREATMENT_TP_1", "code_nm" => "SEDERHANA", "code_group" => "TREATMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TREATMENT_TP_2", "code_nm" => "KECIL", "code_group" => "TREATMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TREATMENT_TP_3", "code_nm" => "SEDANG", "code_group" => "TREATMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TREATMENT_TP_4", "code_nm" => "BESAR", "code_group" => "TREATMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TREATMENT_TP_5", "code_nm" => "KHUSUS", "code_group" => "TREATMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TREATMENT_TP_6", "code_nm" => "CANGGIH", "code_group" => "TREATMENT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TREATMENTSTD_00", "code_nm" => "UMUM", "code_group" => "TREATMENTSTD_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TRXDR_TP_1", "code_nm" => "Visit", "code_group" => "TRXDR_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TRXDR_TP_2", "code_nm" => "Konsultasi", "code_group" => "TRXDR_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TRXDR_TP_3", "code_nm" => "Dokter Rawat", "code_group" => "TRXDR_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VAT_TP_0", "code_nm" => "No VAT", "code_group" => "VAT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VAT_TP_1", "code_nm" => "Include", "code_group" => "VAT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VAT_TP_2", "code_nm" => "Exclude", "code_group" => "VAT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_00", "code_nm" => "BELUM DIKETAHUI", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_01", "code_nm" => "PENYAKIT", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_02", "code_nm" => "KECELAKAAN KERJA", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_03", "code_nm" => "KECELAKAAN LALU LINTAS", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_04", "code_nm" => "KECELAKAAN LAIN-LAIN", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_05", "code_nm" => "VISUM AT REPERTUM", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_06", "code_nm" => "PEMERIKSAAN", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_07", "code_nm" => "KONSULTASI", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_08", "code_nm" => "RUDA PAKSA", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_09", "code_nm" => "KDRT", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_10", "code_nm" => "KRIMINAL", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_11", "code_nm" => "KLB", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_19", "code_nm" => "PERSALINAN", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "VISIT_TP_99", "code_nm" => "BENCANA ALAM", "code_group" => "VISIT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LANGUAGEST_2", "code_nm" => "ENGLISH", "code_group" => "LANGUAGE_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "LANGUAGEST_1", "code_nm" => "INDONESIA", "code_group" => "LANGUAGE_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "LANGUAGEST_3", "code_nm" => "MANDARIN", "code_group" => "LANGUAGE_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "DRTP_1", "code_nm" => "Dokter Rumah Sakit", "code_group" => "DR_TP", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "PARAMEDISST_1", "code_nm" => "Temporary", "code_group" => "PARAMEDIS_TP", "code_value" => "0"]);
        $code = Code::create(["com_cd" => "PARAMEDISST_2", "code_nm" => "Permanen", "code_group" => "PARAMEDIS_TP", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "LANGUAGEST_4", "code_nm" => "BAHASA ARAB", "code_group" => "LANGUAGE_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_12", "code_nm" => "TK", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "EDUCATION_CD_11", "code_nm" => "Dibawah Umur", "code_group" => "EDUCATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "OCCUPATION_CD_15", "code_nm" => "BELUM SEKOLAH", "code_group" => "OCCUPATION_CD", "code_value" => null]);
        $code = Code::create(["com_cd" => "ADMISI_SET_01", "code_nm" => "Hide Biaya Racik", "code_group" => "SETTINGS", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "SEP_SET", "code_nm" => "Setting SEP Otomatis", "code_group" => "SETTINGS", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_1", "code_nm" => "PENYAKIT DALAM ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_2", "code_nm" => "BEDAH", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_3", "code_nm" => "ANAK ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_4", "code_nm" => "OBSETRI (IBU HAMIL) ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_5", "code_nm" => "GINEKOLOGI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_6", "code_nm" => "KB ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_7", "code_nm" => "BEDAH SARAF", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_8", "code_nm" => "SARAF ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_9", "code_nm" => "JIWA ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_10", "code_nm" => "PSIKOLOGI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_11", "code_nm" => "THT ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_12", "code_nm" => "MATA ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_13", "code_nm" => "KULIT DAN KELAMIN ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_14", "code_nm" => "GIGI DAN MULUT ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_15", "code_nm" => "KARDIOLOGI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_16", "code_nm" => "BEDAH ORTHOPEDI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_17", "code_nm" => "PARU-PARU", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_18", "code_nm" => "UMUM ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_19", "code_nm" => "IGD ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_20", "code_nm" => "REHAP MEDIC ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_21", "code_nm" => "AKUPUNTUR ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_22", "code_nm" => "KONSULTASI GIZI", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_23", "code_nm" => "ANDROLOGI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_24", "code_nm" => "ANASTESI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_25", "code_nm" => "BEDAH ANAK ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_26", "code_nm" => "BEDAH DIGESTIF ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_27", "code_nm" => "BEDAH UROLOGI", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_28", "code_nm" => "BEDAH PLASTIK ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_29", "code_nm" => "BEDAH VASKULER", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_30", "code_nm" => "BEDAH UNKOLOGI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_31", "code_nm" => "PARU ASMA ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_32", "code_nm" => "PAIN CLINIC ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_33", "code_nm" => "KEMOTERAPI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_34", "code_nm" => "MCU", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_35", "code_nm" => "PATOLOGI ANATOMI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_36", "code_nm" => "LAKTASI ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_37", "code_nm" => "THALASSEMIA ", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUNJUNGAN_TP_38", "code_nm" => "HEMODIALISA", "code_group" => "KUNJUNGAN_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WHPOS_TRX_01", "code_nm" => "FARMASI", "code_group" => "WHPOS_TRX", "code_value" => "0002"]);
        $code = Code::create(["com_cd" => "APTKR", "code_nm" => "Apoteker", "code_group" => "PARAMEDIS_TP", "code_value" => ""]);
        $code = Code::create(["com_cd" => "OUT_TP_04", "code_nm" => "Meninggal >= 48 Jam", "code_group" => "OUT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "OUT_TP_05", "code_nm" => "Meninggal <= 48 Jam", "code_group" => "OUT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "SVR_RPT", "code_nm" => "Server Report", "code_group" => "SETTINGS", "code_value" => "188.166.215.51:8080"]);
        $code = Code::create(["com_cd" => "MAX_ADM", "code_nm" => "Biaya Administrasi maksimal", "code_group" => "SETTINGS", "code_value" => "1200000"]);
        $code = Code::create(["com_cd" => "BANGSAL_GROUP_01", "code_nm" => "PERAWATAN IBU", "code_group" => "BANGSAL_GROUP", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "BANGSAL_GROUP_02", "code_nm" => "PERAWATAN ANAK", "code_group" => "BANGSAL_GROUP", "code_value" => "2"]);
        $code = Code::create(["com_cd" => "BANGSAL_GROUP_03", "code_nm" => "PERAWATAN UMUM PRIA", "code_group" => "BANGSAL_GROUP", "code_value" => "3"]);
        $code = Code::create(["com_cd" => "BANGSAL_GROUP_04", "code_nm" => "PERAWATAN UMUM WANITA/PEREMPUAN", "code_group" => "BANGSAL_GROUP", "code_value" => "4"]);
        $code = Code::create(["com_cd" => "BANGSAL_GROUP_05", "code_nm" => "PERAWATAN PERINATOLOGI DAN INTENSIF", "code_group" => "BANGSAL_GROUP", "code_value" => "5"]);
        $code = Code::create(["com_cd" => "BIAYA_ADM", "code_nm" => "Biaya Administrasi", "code_group" => "SETTINGS", "code_value" => "7"]);
        $code = Code::create(["com_cd" => "PB_01", "code_nm" => "Progresbar Registrasi", "code_group" => "PROGRES_BARR", "code_value" => "5"]);
        $code = Code::create(["com_cd" => "SERVER_NODE", "code_nm" => "Alamat Server NodeJs", "code_group" => "SETTINGS", "code_value" => "http://188.166.215.51:8890"]);
        $code = Code::create(["com_cd" => "HM_01", "code_nm" => "Jenis Tarif", "code_group" => "GENERATE_TARIF", "code_value" => "3"]);
        $code = Code::create(["com_cd" => "HM_03", "code_nm" => "Jenis Tarif", "code_group" => "GENERATE_TARIF", "code_value" => "7"]);
        $code = Code::create(["com_cd" => "HM_02", "code_nm" => "Jenis Tarif", "code_group" => "GENERATE_TARIF", "code_value" => "5"]);
        $code = Code::create(["com_cd" => "RS_DEF", "code_nm" => "Default Rumah Sakit", "code_group" => "SETTINGS", "code_value" => "001"]);
        $code = Code::create(["com_cd" => "SET_STOCK_BIL", "code_nm" => "Proses Stock Pada billing", "code_group" => "SETTINGS", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "JUMLAH_ITER", "code_nm" => "Jumlah Iter", "code_group" => "SETTINGS", "code_value" => "3"]);
        $code = Code::create(["com_cd" => "WB_TP_01", "code_nm" => "WB O –", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WB_TP_02", "code_nm" => "WB O +", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WB_TP_03", "code_nm" => "WB A –", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WB_TP_04", "code_nm" => "WB A +", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WB_TP_05", "code_nm" => "WB B –", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WB_TP_06", "code_nm" => "WB B +", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WB_TP_07", "code_nm" => "WB AB –", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WB_TP_08", "code_nm" => "WB AB +", "code_group" => "WB_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_01", "code_nm" => "WE O –", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_02", "code_nm" => "WE O +", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_03", "code_nm" => "WE A –", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_04", "code_nm" => "WE A +", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_05", "code_nm" => "WE B –", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_06", "code_nm" => "WE B +", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_07", "code_nm" => "WE AB –", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "WE_TP_08", "code_nm" => "WE AB +", "code_group" => "WE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_01", "code_nm" => "PRC O –", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_02", "code_nm" => "PRC O +", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_03", "code_nm" => "PRC A –", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_04", "code_nm" => "PRC A +", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_05", "code_nm" => "PRC B –", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_06", "code_nm" => "PRC B +", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_07", "code_nm" => "PRC AB –", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRC_TP_08", "code_nm" => "PRC AB +", "code_group" => "PRC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_01", "code_nm" => "LP O –", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_02", "code_nm" => "LP O +", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_03", "code_nm" => "LP A –", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_04", "code_nm" => "LP A +", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_05", "code_nm" => "LP B –", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_06", "code_nm" => "LP B +", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_07", "code_nm" => "LP AB –", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "LP_TP_08", "code_nm" => "LP AB +", "code_group" => "LP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_01", "code_nm" => "TC O –", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_02", "code_nm" => "TC O +", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_03", "code_nm" => "TC A –", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_04", "code_nm" => "TC A +", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_05", "code_nm" => "TC B –", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_06", "code_nm" => "TC B +", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_07", "code_nm" => "TC AB –", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "TC_TP_08", "code_nm" => "TC AB +", "code_group" => "TC_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_01", "code_nm" => "PRP O –", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_02", "code_nm" => "PRP O +", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_03", "code_nm" => "PRP A –", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_04", "code_nm" => "PRP A +", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_05", "code_nm" => "PRP B –", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_06", "code_nm" => "PRP B +", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_07", "code_nm" => "PRP AB –", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "PRP_TP_08", "code_nm" => "PRP AB +", "code_group" => "PRP_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DEF_RWT_GBNG", "code_nm" => "Default Rawat Gabung", "code_group" => "SETTINGS", "code_value" => "50"]);
        $code = Code::create(["com_cd" => "SOURCE_TP_1", "code_nm" => "Pribadi", "code_group" => "SOURCE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "SOURCE_TP_2", "code_nm" => "Institusi", "code_group" => "SOURCE_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "KUI_REG", "code_nm" => "Kuisioner Registrasi", "code_group" => "KUISIONER", "code_value" => "2"]);
        $code = Code::create(["com_cd" => "KUI_JAL", "code_nm" => "Kuisioner Rawat Jalan", "code_group" => "KUISIONER", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "KUI_INA", "code_nm" => "Kuisioner Rawat Inap", "code_group" => "KUISIONER", "code_value" => "3"]);
        $code = Code::create(["com_cd" => "STOCK_DEST_1", "code_nm" => "PMI", "code_group" => "STOCK_DEST", "code_value" => null]);
        $code = Code::create(["com_cd" => "APP_FAVICON", "code_nm" => "FAV ICON ", "code_group" => "APP_SET", "code_value" => "favicon.png"]);
        $code = Code::create(["com_cd" => "APP_RSNAME", "code_nm" => "NAMA RS", "code_group" => "APP_SET", "code_value" => "HERMINA HOSPITAL GROUP"]);
        $code = Code::create(["com_cd" => "APP_NAVLOGO", "code_nm" => "NAVBAR LOGO", "code_group" => "APP_SET", "code_value" => "logo-rs-resizer.png"]);
        $code = Code::create(["com_cd" => "APP_RSLOGO", "code_nm" => "LOGO RS", "code_group" => "APP_SET", "code_value" => "hermina-logo.png"]);
        $code = Code::create(["com_cd" => "DR_PROP_01", "code_nm" => "DOKTER TIDAK JADI PRAKTEK", "code_group" => "DR_PROP", "code_value" => null]);
        $code = Code::create(["com_cd" => "DR_PROP_02", "code_nm" => "MAX PASIEN", "code_group" => "DR_PROP", "code_value" => null]);
        $code = Code::create(["com_cd" => "OK_ROOM_1", "code_nm" => "Ruang Operasi 1", "code_group" => "OK_ROOM", "code_value" => null]);
        $code = Code::create(["com_cd" => "OK_ROOM_2", "code_nm" => "Ruang Operasi 2", "code_group" => "OK_ROOM", "code_value" => null]);
        $code = Code::create(["com_cd" => "VK_ROOM_1", "code_nm" => "Ruang Bersalin 1", "code_group" => "VK_ROOM", "code_value" => null]);
        $code = Code::create(["com_cd" => "VK_ROOM_2", "code_nm" => "Ruang Bersalin 2", "code_group" => "VK_ROOM", "code_value" => null]);
        $code = Code::create(["com_cd" => "BEDAH_ST_1", "code_nm" => "Masih Berlangsung", "code_group" => "BEDAH_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "BEDAH_ST_2", "code_nm" => "Sedang dibersihkan", "code_group" => "BEDAH_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "BEDAH_ST_0", "code_nm" => "Siap Digunakan", "code_group" => "BEDAH_ST", "code_value" => null]);
        $code = Code::create(["com_cd" => "INTEGRATION", "code_nm" => "Integrasi Inventory Ke finance", "code_group" => "SETTINGS", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "OUT_TP_07", "code_nm" => "KABUR", "code_group" => "OUT_TP", "code_value" => null]);
        $code = Code::create(["com_cd" => "MEDICAL_TRX_ST_4", "code_nm" => "Kabur", "code_group" => "MEDICAL_TRX_ST", "code_value" => ""]);
        $code = Code::create(["com_cd" => "APP_LOGOANTRIAN", "code_nm" => "LOGO ANTRIAN", "code_group" => "APP_SET", "code_value" => "logo-rshermina.png"]);
        $code = Code::create(["com_cd" => "PAYOR_3", "code_nm" => "Payor Id", "code_group" => "INA_CBG_PAYOR", "code_value" => "JKN"]);
        $code = Code::create(["com_cd" => "PAYOR_5", "code_nm" => "Payor Id", "code_group" => "INA_CBG_PAYOR", "code_value" => "001"]);
        $code = Code::create(["com_cd" => "PAYOR_6", "code_nm" => "Payor Id", "code_group" => "INA_CBG_PAYOR", "code_value" => "JKS"]);
        $code = Code::create(["com_cd" => "PAYOR_1", "code_nm" => "Payor Id", "code_group" => "INA_CBG_PAYOR", "code_value" => "999"]);
        $code = Code::create(["com_cd" => "KELAS_RAWAT_1", "code_nm" => "Kelas Rawat", "code_group" => "INA_CBG_KELAS_RAWAT", "code_value" => "Eksekutif"]);
        $code = Code::create(["com_cd" => "KELAS_RAWAT_3", "code_nm" => "Kelas Rawat", "code_group" => "INA_CBG_KELAS_RAWAT", "code_value" => "Reguler"]);
        $code = Code::create(["com_cd" => "UP_KELAS_1", "code_nm" => "Upgrade Class Class", "code_group" => "INA_CBG_UP_KELAS", "code_value" => "naik ke kelas 1"]);
        $code = Code::create(["com_cd" => "UP_KELAS_2", "code_nm" => "Upgrade Class Class", "code_group" => "INA_CBG_UP_KELAS", "code_value" => "naik ke kelas 2"]);
        $code = Code::create(["com_cd" => "UP_KELAS_vip", "code_nm" => "Upgrade Class Class", "code_group" => "INA_CBG_UP_KELAS", "code_value" => "naik ke kelas VIP"]);
        $code = Code::create(["com_cd" => "DSCRG_STATUS_1", "code_nm" => "Cara Pulag", "code_group" => "INA_CBG_DSCRG_STATUS", "code_value" => "Atas persetujuan dokter"]);
        $code = Code::create(["com_cd" => "DSCRG_STATUS_2", "code_nm" => "Cara Pulag", "code_group" => "INA_CBG_DSCRG_STATUS", "code_value" => "Dirujuk"]);
        $code = Code::create(["com_cd" => "DSCRG_STATUS_3", "code_nm" => "Cara Pulag", "code_group" => "INA_CBG_DSCRG_STATUS", "code_value" => "Atas permintaan sendiri"]);
        $code = Code::create(["com_cd" => "DSCRG_STATUS_4", "code_nm" => "Cara Pulag", "code_group" => "INA_CBG_DSCRG_STATUS", "code_value" => "Meninggal"]);
        $code = Code::create(["com_cd" => "DSCRG_STATUS_5", "code_nm" => "Cara Pulag", "code_group" => "INA_CBG_DSCRG_STATUS", "code_value" => "Lain-Lain"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_AP", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS A PEMERINTAH"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_AS", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS A SWASTA"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_BP", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS B PEMERINTAH"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_BS", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS B SWASTA"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_CP", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS C PEMERINTAH"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_CS", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS C SWASTA"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_DP", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS D PEMERINTAH"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_DS", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KELAS D SWASTA"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_RSCM", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RSUPN CIPTO MANGUNKUSUMO"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_RSJP", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RSJPD HARAPAN KITA"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_RSD", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RS KANKER DHARMAIS"]);
        $code = Code::create(["com_cd" => "KODE_TARIF_RSAB", "code_nm" => "Kode Tarif", "code_group" => "INA_CBG_KODE_TARIF", "code_value" => "TARIF RSAB HARAPAN KITA"]);
        $code = Code::create(["com_cd" => "INA_MED_TP_01", "code_nm" => "Rawat Jalan", "code_group" => "INA_CBG_MED_TP", "code_value" => "2"]);
        $code = Code::create(["com_cd" => "INA_MED_TP_02", "code_nm" => "Rawat Inap", "code_group" => "INA_CBG_MED_TP", "code_value" => "1"]);
        $code = Code::create(["com_cd" => "ACTIVE_ST_01", "code_nm" => "Digunakan", "code_group" => "ACTIVE_ST"]);
        $code = Code::create(["com_cd" => "ACTIVE_ST_02", "code_nm" => "Tidak Digunakan", "code_group" => "ACTIVE_ST"]);
        $code = Code::create(["com_cd" => "GENERIC_ST_01", "code_nm" => "Paten", "code_group" => "generic_st"]);
        $code = Code::create(["com_cd" => "GENERIC_ST_02", "code_nm" => "Generik", "code_group" => "generic_st"]);
        $code = Code::create(["com_cd" => "CASE_TP_01", "code_nm" => "Baru", "code_group" => "CASE_TP"]);
        $code = Code::create(["com_cd" => "CASE_TP_02", "code_nm" => "Lama", "code_group" => "CASE_TP"]);
        $code = Code::create(["com_cd" => "SUBYEKTIF_TP_01", "code_nm" => "Auto Anamnesa", "code_group" => "SUBYEKTIF_TP"]);
        $code = Code::create(["com_cd" => "SUBYEKTIF_TP_02", "code_nm" => "Allo Anamnesa", "code_group" => "SUBYEKTIF_TP"]);
        $code = Code::create(["com_cd" => "BICARA_TP_01", "code_nm" => "Jelas", "code_group" => "BICARA_TP"]);
        $code = Code::create(["com_cd" => "BICARA_TP_02", "code_nm" => "Tidak Mengerti", "code_group" => "BICARA_TP"]);
        $code = Code::create(["com_cd" => "KOMUNIKASI_TP_01", "code_nm" => "Verbal", "code_group" => "KOMUNIKASI_TP"]);
        $code = Code::create(["com_cd" => "KOMUNIKASI_TP_02", "code_nm" => "Non Verbal", "code_group" => "KOMUNIKASI_TP"]);
        $code = Code::create(["com_cd" => "KOMUNIKASI_TP_03", "code_nm" => "Apatis", "code_group" => "KOMUNIKASI_TP"]);
        $code = Code::create(["com_cd" => "EMOSIONAL_ST_01", "code_nm" => "Stabil", "code_group" => "EMOSIONAL_ST"]);
        $code = Code::create(["com_cd" => "EMOSIONAL_ST_02", "code_nm" => "Marah", "code_group" => "EMOSIONAL_ST"]);
        $code = Code::create(["com_cd" => "EMOSIONAL_ST_03", "code_nm" => "Cemas", "code_group" => "EMOSIONAL_ST"]);
        $code = Code::create(["com_cd" => "EMOSIONAL_ST_04", "code_nm" => "Takut", "code_group" => "EMOSIONAL_ST"]);
        $code = Code::create(["com_cd" => "EMOSIONAL_ST_05", "code_nm" => "Sedih", "code_group" => "EMOSIONAL_ST"]);
        $code = Code::create(["com_cd" => "SOSIOLOGI_TP_01", "code_nm" => "Komunikatif", "code_group" => "SOSIOLOGI_TP"]);
        $code = Code::create(["com_cd" => "SOSIOLOGI_TP_02", "code_nm" => "Menarik Diri", "code_group" => "SOSIOLOGI_TP"]);
        $code = Code::create(["com_cd" => "SOSIOLOGI_TP_03", "code_nm" => "Komunikatif Tidak Efektif", "code_group" => "SOSIOLOGI_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_01", "code_nm" => "Suntik", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_02", "code_nm" => "IUD", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_03", "code_nm" => "Kondom", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_04", "code_nm" => "Pil", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_05", "code_nm" => "Kalender", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_06", "code_nm" => "Implan", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_07", "code_nm" => "MOW", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "RIWAYAT_KB_TP_08", "code_nm" => "Menopause", "code_group" => "RIWAYAT_KB_TP"]);
        $code = Code::create(["com_cd" => "KEHAMILAN_TP_01", "code_nm" => "DM", "code_group" => "KEHAMILAN_TP"]);
        $code = Code::create(["com_cd" => "KEHAMILAN_TP_02", "code_nm" => "Hipertensi", "code_group" => "KEHAMILAN_TP"]);
        $code = Code::create(["com_cd" => "KEHAMILAN_TP_03", "code_nm" => "Hiperemesis", "code_group" => "KEHAMILAN_TP"]);
        $code = Code::create(["com_cd" => "KEHAMILAN_TP_04", "code_nm" => "ISK", "code_group" => "KEHAMILAN_TP"]);
        $code = Code::create(["com_cd" => "KEHAMILAN_TP_05", "code_nm" => "Perdarahan", "code_group" => "KEHAMILAN_TP"]);
        $code = Code::create(["com_cd" => "KEHAMILAN_TP_06", "code_nm" => "Tidak Ada", "code_group" => "RIWAYAT_KEHAMILAN_TP"]);
        $code = Code::create(["com_cd" => "PENGELUARAN_TP_01", "code_nm" => "Pemasukkan", "code_group" => "PENGELUARAN_TP"]);
        $code = Code::create(["com_cd" => "PENGELUARAN_TP_02", "code_nm" => "Pengeluaran", "code_group" => "PENGELUARAN_TP"]);
    }
}
