<?php

namespace Database\Seeders;

use App\Models\His\InvItemMaster;
use App\Models\His\InvPosInventory;
use App\Models\His\InvPosItem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemInvSapuranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['item_cd' => 'A1', 'item_nm' => 'ACT (artesunat 50mg + amudiaquin 200mg)', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A2', 'item_nm' => 'Acyclovir cream', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A3', 'item_nm' => 'Acyclovir tab 200mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A4', 'item_nm' => 'Acyclovir tab 400mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A5', 'item_nm' => 'Akarbose 50 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A6', 'item_nm' => 'Albendazol tab 400 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A7', 'item_nm' => 'Albendazole Suspensi 200 mg/5 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A8', 'item_nm' => 'Alopurinol tab 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A9', 'item_nm' => 'alopurinol tab 300mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A10', 'item_nm' => 'Ambroksol syr 15mg/ 5ml - 60ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A11', 'item_nm' => 'Ambroksol tab 30mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A12', 'item_nm' => 'Aminofilin inj 24 mg/ml 10 mg', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A13', 'item_nm' => 'Aminofilin tab 200 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A14', 'item_nm' => 'Amitriptilin 25 mg tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A15', 'item_nm' => 'amlodipin tab 10mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A16', 'item_nm' => 'amlodipin tab 5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A17', 'item_nm' => 'Amoksisilin drop 100 mg/ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A18', 'item_nm' => 'Amoksisilin kaplet 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A19', 'item_nm' => 'Amoksisilin syr kering 125mg/5ml - 60ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A20', 'item_nm' => 'Amoksisilin syr kering 250mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A21', 'item_nm' => 'Ampicillin inj 1 gr', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A22', 'item_nm' => 'Antasida DOEN Suspensi', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A23', 'item_nm' => 'Antasida DOEN tablet', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A24', 'item_nm' => 'Anti Bakteri DOEN Salep', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A25', 'item_nm' => 'Anti Hemoroid DOEN Supp', 'unit_cd' => 'supp', 'type_cd' => 'obat' ],
            ['item_cd' => 'A26', 'item_nm' => 'Antidiare (kaolin+pectin) syr', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A27', 'item_nm' => 'Antifungi DOEN kombinasi', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A28', 'item_nm' => 'Antimigren DOEN', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A29', 'item_nm' => 'Aqua pro inj steril, bebas pirogen', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A30', 'item_nm' => 'Asam Ascorbat ( Vit C) inj 1000mg/5ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A31', 'item_nm' => 'Asam Ascorbat (Vit C) tab 250 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A32', 'item_nm' => 'Asam Ascorbat (Vit C) tab 50 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A33', 'item_nm' => 'Asam Ascorbat (Vitamin C) Tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A34', 'item_nm' => 'asam asetilsalisilat tab (acetosal) 100mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A35', 'item_nm' => 'asam asetilsalisilat tab (asetosal) 80mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A36', 'item_nm' => 'asam folat tab 1 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A37', 'item_nm' => 'Asam Mefenamat tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A38', 'item_nm' => 'asam nalidiksat 500mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A39', 'item_nm' => 'Asam Pipemidat 400mg tablet', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A40', 'item_nm' => 'Asam traneksamat inj 100 mg/5 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A41', 'item_nm' => 'Asam traneksamat tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A42', 'item_nm' => 'asetazolamid  250mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A43', 'item_nm' => 'atenolol tab 50 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A44', 'item_nm' => 'Atropin Sulfat inj 0,25 mg/ml- 1 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A45', 'item_nm' => 'Attapulgit (Antidiare) tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A46', 'item_nm' => 'Azitromisin Serbuk Injeksi 500 mg', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A47', 'item_nm' => 'Azitromisin tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A48', 'item_nm' => 'Benzatil benzil penicillin inj 2.4 juta IU/vial', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A49', 'item_nm' => 'Betahistin mesilat tab 6mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A50', 'item_nm' => 'Betametason cream 0,05 %', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A51', 'item_nm' => 'Bisacodil tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A52', 'item_nm' => 'bisakodil supp 10mg', 'unit_cd' => 'supp', 'type_cd' => 'obat' ],
            ['item_cd' => 'A53', 'item_nm' => 'Bisakodil supp 5mg', 'unit_cd' => 'supp', 'type_cd' => 'obat' ],
            ['item_cd' => 'A54', 'item_nm' => 'Bisoprolol 5mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A55', 'item_nm' => 'budesonide respules/ cairan inheler 0.25mg/ml', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A56', 'item_nm' => 'Cairan Infus A (KAEN 3A)', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A57', 'item_nm' => 'Cairan Infus B (KAEN 3B)', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A58', 'item_nm' => 'cefadroxil kapsul 500mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A59', 'item_nm' => 'Cefadroxil syr kering 125mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A60', 'item_nm' => 'cefadroxil syr kering 250 mg/ 5 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A61', 'item_nm' => 'CEFIXIM kapsul 100MG', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A62', 'item_nm' => 'cefixim syr 100mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A63', 'item_nm' => 'Cefixime kapsul 200mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A64', 'item_nm' => 'Cefotaxim serbuk inj. 1 mg', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A65', 'item_nm' => 'ceftriakson inj 1 g/vial', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A66', 'item_nm' => 'cetirizine syr 5mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A67', 'item_nm' => 'cetirizine tab 10mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A68', 'item_nm' => 'Cimetidin', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A69', 'item_nm' => 'ciprofloxaxin 500mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A70', 'item_nm' => 'clindamicin kapsul 150MG', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A71', 'item_nm' => 'clindamicin kapsul 300mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A72', 'item_nm' => 'Clopidogrel 75mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A73', 'item_nm' => 'Deksametason inj 5 mg/ml-1 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A74', 'item_nm' => 'Deksametason tab 0,5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A75', 'item_nm' => 'Dewasa  FDC Triple : Tenofovir 300 mg + Lamivudine 300 mg+ Efavirenz 600 mg(tablet)', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A76', 'item_nm' => 'Diazepam inj 5 mg / ml- 2 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A77', 'item_nm' => 'Diazepam lar rectal tube 10 mg/ 2.5ml', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A78', 'item_nm' => 'Diazepam lar rectal tube 5 mg/2,5 ml', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A79', 'item_nm' => 'Diazepam tab 2 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A80', 'item_nm' => 'Diazepam tab 5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A81', 'item_nm' => 'dietilkarbamazin sitrat tab 100mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A82', 'item_nm' => 'Difenhidramin HCl inj 10 mg/ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A83', 'item_nm' => 'Digoksin tab 0,25 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A84', 'item_nm' => 'Diltiasem tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A85', 'item_nm' => 'Diltiazem kaps SR 100 mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A86', 'item_nm' => 'Dimenhidrinat', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A87', 'item_nm' => 'doksisiklin cap 100mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A88', 'item_nm' => 'domperidon syr 5mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A89', 'item_nm' => 'Domperidon tab 10 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A90', 'item_nm' => 'Efavirenz 600mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A91', 'item_nm' => 'Eperison 50mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A92', 'item_nm' => 'Epinefrin HCl (Adrenalin) inj 0,1% - 1 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A93', 'item_nm' => 'Eritromisin kapsul/tablet 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A94', 'item_nm' => 'Eritromisin syr 200mg/5ml - 60ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A95', 'item_nm' => 'Etakridin ( Rivanol ) larutan 0,1 %', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A96', 'item_nm' => 'Etambutol HCl tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A97', 'item_nm' => 'Favirapir tablet 200mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A98', 'item_nm' => 'Fenitoin Natrium kapsul 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A99', 'item_nm' => 'Fenitoin Natrium kapsul 30 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A100', 'item_nm' => 'Fenobarbital inj 50 mg/ml-2ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A101', 'item_nm' => 'Fenobarbital tab 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A102', 'item_nm' => 'Fenobarbital tab 30 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A103', 'item_nm' => 'Fenofibrat 100mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A104', 'item_nm' => 'fenoksimetil penisilin tab 500mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A105', 'item_nm' => 'fenol gliserol (karbogliserin) TT 10%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A106', 'item_nm' => 'Fitomenadion ( Vit K) inj 2 mg/ml 1ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A107', 'item_nm' => 'Fitomenadion ( Vit K1) tab salut 10 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A108', 'item_nm' => 'Flufenazine decanoat inj 25mg/ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A109', 'item_nm' => 'Flunarizine', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A110', 'item_nm' => 'Fluoksetin kaps 20 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A111', 'item_nm' => 'Fluoksetin kapsul 10 mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A112', 'item_nm' => 'Framicetin Sulfat kasa gel', 'unit_cd' => 'sachet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A113', 'item_nm' => 'Furosemid inj i.v/i.m 10mg/ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A114', 'item_nm' => 'Furosemid tab 40 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A115', 'item_nm' => 'Garam oralit kombinasi', 'unit_cd' => 'sachet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A116', 'item_nm' => 'Gemfibrozil 300 mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A117', 'item_nm' => 'Gemfibrozil 600mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A118', 'item_nm' => 'Gentamisin salep kulit 0.1%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A119', 'item_nm' => 'Gentamisin salep mata', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A120', 'item_nm' => 'Gentamisin Tetes Mata 0,3%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A121', 'item_nm' => 'Gentian violet larutan 1 %', 'unit_cd' => 'pot', 'type_cd' => 'obat' ],
            ['item_cd' => 'A122', 'item_nm' => 'Glibenklamidum tab 5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A123', 'item_nm' => 'Glimepiride tab 1 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A124', 'item_nm' => 'Glimepiride tab 2 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A125', 'item_nm' => 'Glimepiride tab 3 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A126', 'item_nm' => 'Glimepiride tab 4 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A127', 'item_nm' => 'Gliseril Guayakolat (GG) tab 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A128', 'item_nm' => 'Glukosa larutan infus 10 % steril 500ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A129', 'item_nm' => 'Glukosa larutan infus 40 % steril 20ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A130', 'item_nm' => 'Glukosa larutan infus 5 % steril 500ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A131', 'item_nm' => 'GOM (Borax Glycerine) 10% 8ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A132', 'item_nm' => 'Griseofulvin (micronized) tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A133', 'item_nm' => 'Griseofulvin 125 mg tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A134', 'item_nm' => 'haloperidol dekanoat inj 50mg/ml-1ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A135', 'item_nm' => 'Haloperidol inj 5mg/ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A136', 'item_nm' => 'Haloperidol tab 1,5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A137', 'item_nm' => 'Haloperidol tab 5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A138', 'item_nm' => 'Heparin gel/salep', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A139', 'item_nm' => 'Hidroklorotiazid ( HCT ) tab 25 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A140', 'item_nm' => 'Hidrokortison cream 2,5 %', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A141', 'item_nm' => 'hidrokortison inj', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A142', 'item_nm' => 'hydroxychloroquine sulfate 200mg tablet', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A143', 'item_nm' => 'Hyoscine-N-Butilbromide', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A144', 'item_nm' => 'Hyoscine-N-Butilbromide inj', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A145', 'item_nm' => 'ibuprofen Suspensi 100mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A146', 'item_nm' => 'Ibuprofen Suspensi 200mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A147', 'item_nm' => 'Ibuprofen tab 200 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A148', 'item_nm' => 'Ibuprofen tab 400 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A149', 'item_nm' => 'Ipratropium bromida nebulizer 0,025%', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A150', 'item_nm' => 'Isoniazida ( INH ) tab 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A151', 'item_nm' => 'Isoniazida ( INH ) tab 300 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A152', 'item_nm' => 'Isosorbid dinitrat tab sublingual 5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A153', 'item_nm' => 'Kalamin Lotio', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A154', 'item_nm' => 'kalium aspartat 300mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A155', 'item_nm' => 'Kalsium Glukonas inj', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A156', 'item_nm' => 'Kalsium Lactat ( Kalk ) tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A157', 'item_nm' => 'kanamisin inj I Gram', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A158', 'item_nm' => 'Kaptopril tab 12,5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A159', 'item_nm' => 'Kaptopril tab 25 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A160', 'item_nm' => 'Karbamazepin tab 200 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A161', 'item_nm' => 'karbon aktif tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A162', 'item_nm' => 'Ketokonazol cream 2%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A163', 'item_nm' => 'Ketokonazol scalp solution 2%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A164', 'item_nm' => 'ketokonazol tab 200mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A165', 'item_nm' => 'Ketoprofen suppositoria', 'unit_cd' => 'supp', 'type_cd' => 'obat' ],
            ['item_cd' => 'A166', 'item_nm' => 'Ketorolac inj 30mg', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A167', 'item_nm' => 'klofazimin kapsul 100mg microzine', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A168', 'item_nm' => 'Kloramfenikol + prednisolon cream', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A169', 'item_nm' => 'Kloramfenikol kapsul 250mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A170', 'item_nm' => 'Kloramfenikol kapsul 500mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A171', 'item_nm' => 'Kloramfenikol salep kulit 2%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A172', 'item_nm' => 'Kloramfenikol Salep Mata 1 %', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A173', 'item_nm' => 'Kloramfenikol syr 125mg/ 5ml - 60ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A174', 'item_nm' => 'Kloramfenikol Tetes Mata 0.5%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A175', 'item_nm' => 'Kloramfenikol Tetes Telinga 1 %', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A176', 'item_nm' => 'Klorfeniramin Maleat ( CTM ) tab 4 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A177', 'item_nm' => 'Klorokuin fosfat tab 150 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A178', 'item_nm' => 'Klorpromazin HCl inj 25 mg/ml- 1 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A179', 'item_nm' => 'Klorpromazin HCl tab 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A180', 'item_nm' => 'Klozapin tab 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A181', 'item_nm' => 'Klozapin tab 25 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A182', 'item_nm' => 'kodein tab 10mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A183', 'item_nm' => 'Kolkisin tab 0,5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A184', 'item_nm' => 'Kombinasi : Antibiotik+Kortikosteroid Tetes Mata', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A185', 'item_nm' => 'Kombinasi : ipatropium bromida 0.5mg, salbutamol 2.5mg lar ih', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A186', 'item_nm' => 'kombinasi : parafin, Phenolphtaline, glycerol emulsi', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A187', 'item_nm' => 'Kombinasi ATP 20mg, Vit B1, B6, B12, vit E', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A188', 'item_nm' => 'Kombinasi diastase + pranketin/protease', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A189', 'item_nm' => 'kombinasi dl-methionine 100 mg, choline bitartrate 100 mg + multivitamin', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A190', 'item_nm' => 'kombinasi ekstrak kumis kucing, tempuyung, kejibeling, meniran (nephrolit)', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A191', 'item_nm' => 'kombinasi pyratiazine + vit b6', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A192', 'item_nm' => 'Kotrimoksasol dewasa 480mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A193', 'item_nm' => 'Kotrimoksasol Forte 960mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A194', 'item_nm' => 'Kotrimoksasol Syr 240mg/5ml - 60ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A195', 'item_nm' => 'Kuetiapin fumarat SR 400mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A196', 'item_nm' => 'lactobacillus serbuk', 'unit_cd' => 'sachet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A197', 'item_nm' => 'laktulosa sir 10g/15ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A198', 'item_nm' => 'Lamivudin (3TC) 150mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A199', 'item_nm' => 'lansoprazole kapsul 30mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A200', 'item_nm' => 'Levofloxacin 750 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A201', 'item_nm' => 'Levofloxacin infus 750 mg/150 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A202', 'item_nm' => 'Levofloxacin tab 500mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A203', 'item_nm' => 'Lidokain + epineprin inj', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A204', 'item_nm' => 'Lidokain gelli 2%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A205', 'item_nm' => 'Lidokain murni inj 2 %', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A206', 'item_nm' => 'Lisinopril tab 5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A207', 'item_nm' => 'litium karbonat 200mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A208', 'item_nm' => 'Loperamide', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A209', 'item_nm' => 'Lopinavir 200 mg Ritonavir(LPV/r) 50 mg (ALUVIA)', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A210', 'item_nm' => 'Loratadine', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A211', 'item_nm' => 'Magnesium sulfa inj (IV) 20 % / 25 ml', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A212', 'item_nm' => 'Magnesium sulfa inj (IV) 40 % / 25 ml', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A213', 'item_nm' => 'Meloksikam tab 15 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A214', 'item_nm' => 'Metformin 500mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A215', 'item_nm' => 'Metformin 850mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A216', 'item_nm' => 'Metildopa tab 250 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A217', 'item_nm' => 'Metilergometrin Maleat inj 0,200 mg - 1 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A218', 'item_nm' => 'Metilergometrin Maleat tab 0,125 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A219', 'item_nm' => 'Metilprednisolon inj 125mg', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A220', 'item_nm' => 'metilprednisolon tab 4 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A221', 'item_nm' => 'Metochlorpropramide inj', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A222', 'item_nm' => 'Metochlorpropramide tab 10 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A223', 'item_nm' => 'metronidazole infus 5mg/ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A224', 'item_nm' => 'Metronidazole suppositoria 500 mg', 'unit_cd' => 'supp', 'type_cd' => 'obat' ],
            ['item_cd' => 'A225', 'item_nm' => 'Metronidazole syr', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A226', 'item_nm' => 'Metronidazole tab 250 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A227', 'item_nm' => 'Metronidazole tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A228', 'item_nm' => 'Mikonazol cream/salep 2% (nitrat)', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A229', 'item_nm' => 'Mikonazol serb 2%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A230', 'item_nm' => 'mineral mix sachet /8gr', 'unit_cd' => 'sachet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A231', 'item_nm' => 'mometason cream 0,1%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A232', 'item_nm' => 'multivitamin + Hepatoprotektor syr', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A233', 'item_nm' => 'multivitamin syr', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A234', 'item_nm' => 'multivitamin tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A235', 'item_nm' => 'N-asetil sistein tab 200mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A236', 'item_nm' => 'Natrium Bikarbonat tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A237', 'item_nm' => 'Natrium Diklofenak tab 25mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A238', 'item_nm' => 'Natrium Diklofenak tab 50 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A239', 'item_nm' => 'Natrium Fusidat Salep 2%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A240', 'item_nm' => 'Natrium Klorida larutan infus 0,9 %', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A241', 'item_nm' => 'natrium tiroksian tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A242', 'item_nm' => 'Neurotropik tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A243', 'item_nm' => 'Nevirapine 200mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A244', 'item_nm' => 'Nifedipin tab 10 MG', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A245', 'item_nm' => 'Nifedipin tab 20 mg lepas lambat (orros)', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A246', 'item_nm' => 'nistatin suspensi 100.000 ui/ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A247', 'item_nm' => 'Nistatin tab salut gula 500.000 IU / mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A248', 'item_nm' => 'Nistatin vaginal tab 100.000 IU / mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A249', 'item_nm' => 'OAT FDC anak', 'unit_cd' => 'paket', 'type_cd' => 'obat' ],
            ['item_cd' => 'A250', 'item_nm' => 'OAT FDC kategori 1', 'unit_cd' => 'paket', 'type_cd' => 'obat' ],
            ['item_cd' => 'A251', 'item_nm' => 'OAT FDC kategori 2', 'unit_cd' => 'paket', 'type_cd' => 'obat' ],
            ['item_cd' => 'A252', 'item_nm' => 'OAT kombipak Kategori 1 dewasa', 'unit_cd' => 'paket', 'type_cd' => 'obat' ],
            ['item_cd' => 'A253', 'item_nm' => 'OAT kombipak Kategori 2 dewasa', 'unit_cd' => 'paket', 'type_cd' => 'obat' ],
            ['item_cd' => 'A254', 'item_nm' => 'OAT kombipak kategori anak', 'unit_cd' => 'paket', 'type_cd' => 'obat' ],
            ['item_cd' => 'A255', 'item_nm' => 'Obat Anti Malaria Kombinasi DHP (Dihydroartemisinin Piperaquine )', 'unit_cd' => 'paket', 'type_cd' => 'obat' ],
            ['item_cd' => 'A256', 'item_nm' => 'Obat Batuk Hitam ( OBH )', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A257', 'item_nm' => 'obat batuk kombinasi tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A258', 'item_nm' => 'obat batuk syr kombinasi', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A259', 'item_nm' => 'obat flu kombinasi syr (triprolidin+pseudiefedrin)', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A260', 'item_nm' => 'obat flu kombinasi tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A261', 'item_nm' => 'Obat Flu syr + Parasetamol', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A262', 'item_nm' => 'Obat MDT Kusta MB Anak (dapson)', 'unit_cd' => 'strip', 'type_cd' => 'obat' ],
            ['item_cd' => 'A263', 'item_nm' => 'Obat MDT Kusta MB Dewasa (dapson)', 'unit_cd' => 'strip', 'type_cd' => 'obat' ],
            ['item_cd' => 'A264', 'item_nm' => 'Obat MDT Kusta PB Anak (dapson)', 'unit_cd' => 'strip', 'type_cd' => 'obat' ],
            ['item_cd' => 'A265', 'item_nm' => 'Obat MDT Kusta PB Dewasa', 'unit_cd' => 'strip', 'type_cd' => 'obat' ],
            ['item_cd' => 'A266', 'item_nm' => 'ofloxacin tablet salut selaput 400 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A267', 'item_nm' => 'oksigen gas medis', 'unit_cd' => 'liter', 'type_cd' => 'obat' ],
            ['item_cd' => 'A268', 'item_nm' => 'Oksitetrasiklin HCL salep kulit 3 %', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A269', 'item_nm' => 'Oksitetrasiklin HCL salep mata 1 %', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A270', 'item_nm' => 'Oksitoksin inj 10 IU/ ml - 1 ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A271', 'item_nm' => 'omeprazole inj', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A272', 'item_nm' => 'omeprazole kapsul 20mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A273', 'item_nm' => 'Ondansetron inj', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A274', 'item_nm' => 'Ondansetron tab 8 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A275', 'item_nm' => 'Oseltamivir', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A276', 'item_nm' => 'Papaverin tab 40mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A277', 'item_nm' => 'Parasetamol drop', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A278', 'item_nm' => 'Parasetamol infus 1gr/100ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A279', 'item_nm' => 'Parasetamol rectal tube 125mg /2.5ml', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A280', 'item_nm' => 'Parasetamol syr 120mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A281', 'item_nm' => 'Parasetamol tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A282', 'item_nm' => 'pediatrik FDC Triple : Zidovudine 60mg + lamifudine 30mg + nevirapin 50mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A283', 'item_nm' => 'Perak Sulfadiazin cream 1 %', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A284', 'item_nm' => 'Permetrin cream 5% 10gr', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A285', 'item_nm' => 'Permetrin solution 1%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A286', 'item_nm' => 'pilocarpin tetes mata 2 % (HCl/nitrat)', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A287', 'item_nm' => 'Piracetam inj 1g/5ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A288', 'item_nm' => 'Piracetam tab 800mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A289', 'item_nm' => 'Piridoxin HCL (vit B 6) tab 10 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A290', 'item_nm' => 'Piridoxin HCL (vit B 6) tab 25 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A291', 'item_nm' => 'Piroxicam 20mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A292', 'item_nm' => 'Povidon Iodine 10% 30 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A293', 'item_nm' => 'Povidon Iodine 10% 1000 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A294', 'item_nm' => 'Povidon Iodine 10% 300 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A295', 'item_nm' => 'Prednison tab 5 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A296', 'item_nm' => 'Primakuin tab 15 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A297', 'item_nm' => 'Probenesid tab 500 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A298', 'item_nm' => 'Prokain Benzil Penisillin 3 jt IU', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A299', 'item_nm' => 'Propiltiourasil tab 100 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A300', 'item_nm' => 'Propranolol HCL tab 10 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A301', 'item_nm' => 'Propranolol HCL tab 40 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A302', 'item_nm' => 'Pyrazinamid 500mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A303', 'item_nm' => 'Quetiapine Tab SR 400 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A304', 'item_nm' => 'Ranitidin inj 25mg/ml@1ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A305', 'item_nm' => 'Ranitidin tab 150mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A306', 'item_nm' => 'Remdesivir Serbuk Injeksi 100 mg', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A307', 'item_nm' => 'Retinol 100.000 UI', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A308', 'item_nm' => 'Retinol 200.000 UI', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A309', 'item_nm' => 'Rifampicin 450MG', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A310', 'item_nm' => 'Rifampicin 600 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A311', 'item_nm' => 'Ringer Asetat infus steril', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A312', 'item_nm' => 'Ringer Asetat infus steril + asam malat', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A313', 'item_nm' => 'Ringer lactat ( RL ) infus steril', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A314', 'item_nm' => 'ripivirine 25 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A315', 'item_nm' => 'risperidon tab 2 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A316', 'item_nm' => 'Salbutamol lar respirator utk nebulizer 1 mg/ml', 'unit_cd' => 'ampul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A317', 'item_nm' => 'Salbutamol sir 2 mg/5 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A318', 'item_nm' => 'Salbutamol tab 2 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A319', 'item_nm' => 'Salbutamol tab 4 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A320', 'item_nm' => 'Salep 2 - 4', 'unit_cd' => 'pot', 'type_cd' => 'obat' ],
            ['item_cd' => 'A321', 'item_nm' => 'Salisil bedak 2 %', 'unit_cd' => 'pack', 'type_cd' => 'obat' ],
            ['item_cd' => 'A322', 'item_nm' => 'Sianokobalamin (B 12) tab 50mcg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A323', 'item_nm' => 'simvastatin tab 10mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A324', 'item_nm' => 'Simvastatin tab sal 20 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A325', 'item_nm' => 'Spironolacton tab 100mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A326', 'item_nm' => 'Spironolacton tab 25mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A327', 'item_nm' => 'streptomisin serbuk inj 1gr/vial', 'unit_cd' => 'vial', 'type_cd' => 'obat' ],
            ['item_cd' => 'A328', 'item_nm' => 'sukralfat 500mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A329', 'item_nm' => 'sukralfat syr 500mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A330', 'item_nm' => 'Tambah darah kombinasi ( ferro fumarat 60 mg, asam folat 0,4 mg)', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A331', 'item_nm' => 'Tambah Darah kombinasi tab (ferro fumarat + multivitamin)', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A332', 'item_nm' => 'Tenofovir (QTDF) 300mg + emtricitabine 200mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A333', 'item_nm' => 'Tenofovir (TDF) 300mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A334', 'item_nm' => 'Tetrakain HCl tetes mata 0.5%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A335', 'item_nm' => 'Tetrasiklin kapsul 500mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A336', 'item_nm' => 'Theophilin', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A337', 'item_nm' => 'Tiamfenikol 500mg', 'unit_cd' => 'kapsul', 'type_cd' => 'obat' ],
            ['item_cd' => 'A338', 'item_nm' => 'Tiamin HCL (B 1) tab 50 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A339', 'item_nm' => 'Timolol tts mata 0,5%', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A340', 'item_nm' => 'triamsinolon asetonida oral base 1%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A341', 'item_nm' => 'Triheksifenidil HCl 2 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A342', 'item_nm' => 'Urea cream 2%', 'unit_cd' => 'tube', 'type_cd' => 'obat' ],
            ['item_cd' => 'A343', 'item_nm' => 'Valproat sir 250 mg/5 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A344', 'item_nm' => 'Valproat tab SR 250 mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A345', 'item_nm' => 'Valsaltran 80mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A346', 'item_nm' => 'VALSARTAN 160 MG', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A347', 'item_nm' => 'Vitamin B kompleks tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A348', 'item_nm' => 'Vitamin D3 1000 UI', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A349', 'item_nm' => 'zidovudine', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A350', 'item_nm' => 'Zidovudine + Lamivudine (300mg/150mg)', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A351', 'item_nm' => 'Zidovudine(ZDV) 60mg+Lamivudine(3TC) 30 mg+ Nevirapine(NVP) 50mg', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
            ['item_cd' => 'A352', 'item_nm' => 'Zinc drops 10 mg/ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A353', 'item_nm' => 'Zink Sirup 10mg/5ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A354', 'item_nm' => 'Zink Sirup 20mg/5 ml', 'unit_cd' => 'botol', 'type_cd' => 'obat' ],
            ['item_cd' => 'A355', 'item_nm' => 'Zink tab', 'unit_cd' => 'tablet', 'type_cd' => 'obat' ],
        ];

    $inventori = InvPosInventory::all();

    foreach($data as $datum) {
        InvItemMaster::create($datum);

        foreach($inventori as $item) {
            $cek = InvPosItem::where('pos_cd', $item->pos_cd)->where('item_cd', $datum['item_cd'])->first();
            if(!$cek){
                InvPosItem::create([
                    'pos_cd' => $item->pos_cd,
                    'item_cd' => $datum['item_cd'],
                    'quantity' => 0
                ]);
            }
        }

    }
    }
}
