<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\His\ComNation;

class NationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["nation_cd" => "1", "nation_nm" => "USA", "capital" => "WASHINGTON, DC"],
            ["nation_cd" => "102", "nation_nm" => "ANTIGUA", "capital" => "ST. JOHN'S"],
            ["nation_cd" => "103", "nation_nm" => "BAHAMAS", "capital" => "NASSAU"],
            ["nation_cd" => "104", "nation_nm" => "BARBADOS", "capital" => "BRIDGETOWN"],
            ["nation_cd" => "109", "nation_nm" => "DOMINICA", "capital" => "ROSEAU"],
            ["nation_cd" => "11", "nation_nm" => "CANADA", "capital" => "OTTAWA"],
            ["nation_cd" => "110", "nation_nm" => "DOMINICAN REP.", "capital" => "SANTO DOMINGO"],
            ["nation_cd" => "111", "nation_nm" => "GRENADA ST.", "capital" => "GEORGE'S"],
            ["nation_cd" => "112", "nation_nm" => "JAMAICA", "capital" => "KINGSTON"],
            ["nation_cd" => "117", "nation_nm" => "TRINIDAD & TOBAGO", "capital" => "PORT-OF-SPAIN"],
            ["nation_cd" => "120", "nation_nm" => "BARBUDA", "capital" => "CODRINGTON"],
            ["nation_cd" => "20", "nation_nm" => "EGYPT", "capital" => "CAIRO"],
            ["nation_cd" => "212", "nation_nm" => "MOROCCO", "capital" => "RABAT"],
            ["nation_cd" => "213", "nation_nm" => "ALGERIA", "capital" => "ALGIERS"],
            ["nation_cd" => "216", "nation_nm" => "TUNISIA", "capital" => "TUNIS"],
            ["nation_cd" => "218", "nation_nm" => "LIBYAN ARAB JAMAHIRIYA", "capital" => "TRIPOLI"],
            ["nation_cd" => "220", "nation_nm" => "GAMBIA", "capital" => "BANJUL"],
            ["nation_cd" => "221", "nation_nm" => "SENEGAL", "capital" => "DAKAR"],
            ["nation_cd" => "222", "nation_nm" => "MAURITANIA", "capital" => "NOUAKCHOTT"],
            ["nation_cd" => "223", "nation_nm" => "MALI", "capital" => "BAMAKO"],
            ["nation_cd" => "224", "nation_nm" => "GUINEA", "capital" => "CONAKRY"],
            ["nation_cd" => "226", "nation_nm" => "BURKINA FASO", "capital" => "OUAGADOUGOU"],
            ["nation_cd" => "227", "nation_nm" => "NIGER", "capital" => "NIAMEY"],
            ["nation_cd" => "228", "nation_nm" => "TOGO", "capital" => "LOME"],
            ["nation_cd" => "229", "nation_nm" => "BENIN", "capital" => "COTONOU"],
            ["nation_cd" => "230", "nation_nm" => "MAURITIUS", "capital" => "PORT LOUIS"],
            ["nation_cd" => "231", "nation_nm" => "LIBERIA", "capital" => "MONROVIA"],
            ["nation_cd" => "232", "nation_nm" => "SIERRA LEONE", "capital" => "FREETOWN"],
            ["nation_cd" => "233", "nation_nm" => "GHANA", "capital" => "ACCRA"],
            ["nation_cd" => "234", "nation_nm" => "NIGERIA", "capital" => "ABUJA"],
            ["nation_cd" => "235", "nation_nm" => "CHAD", "capital" => "N'DJAMENA"],
            ["nation_cd" => "236", "nation_nm" => "CENTRAL AFRICAN REP.", "capital" => "BANGUI"],
            ["nation_cd" => "237", "nation_nm" => "CAMEROON", "capital" => "YAOUNDE"],
            ["nation_cd" => "238", "nation_nm" => "CAPE VERDE ISLANDS", "capital" => "PRAIA"],
            ["nation_cd" => "239", "nation_nm" => "SAO TOME & PRINCIPE", "capital" => "SAO TOME"],
            ["nation_cd" => "240", "nation_nm" => "EQUATORIAL GUINEA", "capital" => "MALABO"],
            ["nation_cd" => "241", "nation_nm" => "GABON", "capital" => "LIBREVILLE"],
            ["nation_cd" => "242", "nation_nm" => "CONGO, REP. OF THE", "capital" => "BRAZZAVILLE"],
            ["nation_cd" => "244", "nation_nm" => "ANGOLA", "capital" => "LUANDA"],
            ["nation_cd" => "245", "nation_nm" => "GUINEA-BISSAU", "capital" => "BISSAU"],
            ["nation_cd" => "248", "nation_nm" => "SEYCHELLES", "capital" => "VICTORIA"],
            ["nation_cd" => "249", "nation_nm" => "SUDAN", "capital" => "KHARTOUM"],
            ["nation_cd" => "250", "nation_nm" => "RWANDA", "capital" => "KIGALI"],
            ["nation_cd" => "251", "nation_nm" => "ETHIOPIA", "capital" => "ADDIS ABABA"],
            ["nation_cd" => "252", "nation_nm" => "SOMALIA", "capital" => "MOGADISHU"],
            ["nation_cd" => "253", "nation_nm" => "DJIBOUTI", "capital" => "DJIBOUTI"],
            ["nation_cd" => "254", "nation_nm" => "KENYA", "capital" => "NAIROBI"],
            ["nation_cd" => "255", "nation_nm" => "TANZANIA", "capital" => "DODOMA"],
            ["nation_cd" => "256", "nation_nm" => "UGANDA", "capital" => "KAMPALA"],
            ["nation_cd" => "257", "nation_nm" => "BURUNDI", "capital" => "BUJUMBURA"],
            ["nation_cd" => "258", "nation_nm" => "MOZAMBIQUE", "capital" => "MAPUTO"],
            ["nation_cd" => "260", "nation_nm" => "ZAMBIA", "capital" => "LUSAKA"],
            ["nation_cd" => "261", "nation_nm" => "MADAGASCAR", "capital" => "ANTANANARIVO"],
            ["nation_cd" => "263", "nation_nm" => "ZIMBABWE", "capital" => "HARARE"],
            ["nation_cd" => "264", "nation_nm" => "NAMIBIA", "capital" => "WINDHOEK"],
            ["nation_cd" => "265", "nation_nm" => "MALAWI", "capital" => "LILONGWE"],
            ["nation_cd" => "266", "nation_nm" => "LESOTHO", "capital" => "MASERU"],
            ["nation_cd" => "267", "nation_nm" => "BOTSWANA", "capital" => "GABORONE"],
            ["nation_cd" => "268", "nation_nm" => "SWAZILAND", "capital" => "MBABANE"],
            ["nation_cd" => "269", "nation_nm" => "COMOROS", "capital" => "MORONI"],
            ["nation_cd" => "27", "nation_nm" => "SOUTH AFRICA", "capital" => "CAPE TOWN"],
            ["nation_cd" => "291", "nation_nm" => "ERITREA", "capital" => "ASMARA"],
            ["nation_cd" => "30", "nation_nm" => "GREECE", "capital" => "ATHENS"],
            ["nation_cd" => "31", "nation_nm" => "NETHERLANDS", "capital" => "THE HAGUE"],
            ["nation_cd" => "32", "nation_nm" => "BELGIUM", "capital" => "BRUSSELS"],
            ["nation_cd" => "33", "nation_nm" => "FRANCE", "capital" => "PARIS"],
            ["nation_cd" => "34", "nation_nm" => "SPAIN", "capital" => "MADRID"],
            ["nation_cd" => "351", "nation_nm" => "PORTUGAL", "capital" => "LISBON"],
            ["nation_cd" => "352", "nation_nm" => "LUXEMBOURG", "capital" => "LUXEMBOURG"],
            ["nation_cd" => "353", "nation_nm" => "IRELAND", "capital" => "DUBLIN"],
            ["nation_cd" => "354", "nation_nm" => "ICELAND", "capital" => "REYKJAVIK"],
            ["nation_cd" => "355", "nation_nm" => "ALBANIA", "capital" => "TIRANE"],
            ["nation_cd" => "356", "nation_nm" => "MALTA", "capital" => "VALLETTA"],
            ["nation_cd" => "357", "nation_nm" => "CYPRUS", "capital" => "NICOSIA"],
            ["nation_cd" => "358", "nation_nm" => "FINLAND", "capital" => "HELSINKI"],
            ["nation_cd" => "359", "nation_nm" => "BULGARIA", "capital" => "SOFIA"],
            ["nation_cd" => "36", "nation_nm" => "HUNGARY", "capital" => "BUDAPEST"],
            ["nation_cd" => "370", "nation_nm" => "LITHUANIA", "capital" => "VILNIUS"],
            ["nation_cd" => "371", "nation_nm" => "LATVIA", "capital" => "RIGA"],
            ["nation_cd" => "372", "nation_nm" => "ESTONIA", "capital" => "TALLINN"],
            ["nation_cd" => "373", "nation_nm" => "MOLDOVA, REP. OF", "capital" => "CHISINAU"],
            ["nation_cd" => "374", "nation_nm" => "ARMENIA", "capital" => "YEREVAN"],
            ["nation_cd" => "375", "nation_nm" => "BELARUS", "capital" => "MINSK"],
            ["nation_cd" => "376", "nation_nm" => "ANDORRA", "capital" => "ANDORRA LA VELLA"],
            ["nation_cd" => "377", "nation_nm" => "MONACO", "capital" => "MONACO"],
            ["nation_cd" => "378", "nation_nm" => "SAN MARINO", "capital" => "SAN MARINO"],
            ["nation_cd" => "380", "nation_nm" => "UKRAINE", "capital" => "KIEV"],
            ["nation_cd" => "385", "nation_nm" => "CROATIA", "capital" => "ZAGREB"],
            ["nation_cd" => "386", "nation_nm" => "SLOVENIA", "capital" => "LJUBLJANA"],
            ["nation_cd" => "387", "nation_nm" => "BOSNIA - HERZEGOVINA", "capital" => "SARAJEVO"],
            ["nation_cd" => "389", "nation_nm" => "MACEDONIA (F.Y.R.O.M.)", "capital" => "SKOPJE"],
            ["nation_cd" => "39", "nation_nm" => "ITALY", "capital" => "ROME"],
            ["nation_cd" => "40", "nation_nm" => "ROMANIA", "capital" => "BUCHAREST"],
            ["nation_cd" => "41", "nation_nm" => "SWITZERLAND", "capital" => "BERN"],
            ["nation_cd" => "411", "nation_nm" => "LIECHTENSTEIN", "capital" => "VADUZ"],
            ["nation_cd" => "420", "nation_nm" => "CZECH REP.", "capital" => "PRAGUE"],
            ["nation_cd" => "421", "nation_nm" => "SLOVAKIA", "capital" => "BRATISLAVA"],
            ["nation_cd" => "43", "nation_nm" => "AUSTRIA", "capital" => "VIENNA"],
            ["nation_cd" => "44", "nation_nm" => "UNITED KINGDOM", "capital" => "LONDON"],
            ["nation_cd" => "441", "nation_nm" => "WALES", "capital" => "CARDIFF"],
            ["nation_cd" => "442", "nation_nm" => "SCOTLAND", "capital" => "EDINBURGH"],
            ["nation_cd" => "45", "nation_nm" => "DENMARK", "capital" => "COPENHAGEN"],
            ["nation_cd" => "46", "nation_nm" => "SWEDEN", "capital" => "STOCKHOLM"],
            ["nation_cd" => "47", "nation_nm" => "NORWAY", "capital" => "OSLO"],
            ["nation_cd" => "48", "nation_nm" => "POLAND", "capital" => "WARSAW"],
            ["nation_cd" => "49", "nation_nm" => "GERMANY", "capital" => "BERLIN"],
            ["nation_cd" => "501", "nation_nm" => "BELIZE", "capital" => "BELMOPAN"],
            ["nation_cd" => "502", "nation_nm" => "GUATEMALA", "capital" => "GUATEMALA CITY"],
            ["nation_cd" => "503", "nation_nm" => "EL SALVADOR", "capital" => "SAN SALVADOR"],
            ["nation_cd" => "504", "nation_nm" => "HONDURAS", "capital" => "TEGUCIGALPA"],
            ["nation_cd" => "505", "nation_nm" => "NICARAGUA", "capital" => "MANAGUA"],
            ["nation_cd" => "506", "nation_nm" => "COSTA RICA", "capital" => "SAN JOSE"],
            ["nation_cd" => "507", "nation_nm" => "PANAMA", "capital" => "PANAMA CITY"],
            ["nation_cd" => "509", "nation_nm" => "HAITI", "capital" => "PORT-AU-PRINCE"],
            ["nation_cd" => "51", "nation_nm" => "PERU", "capital" => "LIMA"],
            ["nation_cd" => "52", "nation_nm" => "MEXICO", "capital" => "MEXICO CITY"],
            ["nation_cd" => "53", "nation_nm" => "CUBA", "capital" => "HAVANA"],
            ["nation_cd" => "54", "nation_nm" => "ARGENTINA", "capital" => "BUENOS AIRES"],
            ["nation_cd" => "55", "nation_nm" => "BRAZIL", "capital" => "BRASILIA"],
            ["nation_cd" => "56", "nation_nm" => "CHILE, REP. OF", "capital" => "SANTIAGO"],
            ["nation_cd" => "57", "nation_nm" => "COLOMBIA", "capital" => "BOGOTA"],
            ["nation_cd" => "58", "nation_nm" => "VENEZUELA", "capital" => "CARACAS"],
            ["nation_cd" => "591", "nation_nm" => "BOLIVIA", "capital" => "SUCRE"],
            ["nation_cd" => "592", "nation_nm" => "GUYANA", "capital" => "GEORGETOWN"],
            ["nation_cd" => "593", "nation_nm" => "ECUADOR", "capital" => "QUITO"],
            ["nation_cd" => "595", "nation_nm" => "PARAGUAY", "capital" => "ASUNCION"],
            ["nation_cd" => "597", "nation_nm" => "SURINAME", "capital" => "PARAMARIBO"],
            ["nation_cd" => "598", "nation_nm" => "URUGUAY", "capital" => "MONTEVIDEO"],
            ["nation_cd" => "599", "nation_nm" => "NETHERLANDS ANTILLES", "capital" => "AMSTERDAM"],
            ["nation_cd" => "60", "nation_nm" => "MALAYSIA", "capital" => "KUALA LUMPUR"],
            ["nation_cd" => "61", "nation_nm" => "AUSTRALIA", "capital" => "CANBERRA"],
            ["nation_cd" => "62", "nation_nm" => "INDONESIA", "capital" => "JAKARTA"],
            ["nation_cd" => "63", "nation_nm" => "PHILIPPINES", "capital" => "MANILA"],
            ["nation_cd" => "64", "nation_nm" => "NEW ZEALAND", "capital" => "WELLINGTON"],
            ["nation_cd" => "65", "nation_nm" => "SINGAPORE", "capital" => "SINGAPORE"],
            ["nation_cd" => "66", "nation_nm" => "THAILAND", "capital" => "BANGKOK"],
            ["nation_cd" => "673", "nation_nm" => "BRUNEI", "capital" => "BANDAR SERI BEGAWAN"],
            ["nation_cd" => "674", "nation_nm" => "NAURU", "capital" => "YAREN"],
            ["nation_cd" => "675", "nation_nm" => "PAPUA NEW GUINEA", "capital" => "PORT MORESBY"],
            ["nation_cd" => "676", "nation_nm" => "TONGA", "capital" => "NUKU'ALOFA"],
            ["nation_cd" => "677", "nation_nm" => "SOLOMON ISLANDS", "capital" => "HONIARA"],
            ["nation_cd" => "678", "nation_nm" => "VANUATU", "capital" => "PORT VILA"],
            ["nation_cd" => "679", "nation_nm" => "FIJI", "capital" => "SUVA"],
            ["nation_cd" => "680", "nation_nm" => "PALAU", "capital" => "KOROR"],
            ["nation_cd" => "685", "nation_nm" => "WESTERN SAMOA", "capital" => "APIA"],
            ["nation_cd" => "686", "nation_nm" => "KIRIBATI", "capital" => "TARAWA"],
            ["nation_cd" => "688", "nation_nm" => "TUVALU", "capital" => "FUNAFUTI"],
            ["nation_cd" => "691", "nation_nm" => "MICRONESIA, FEDERATED STATES OF", "capital" => "PALIKIR"],
            ["nation_cd" => "692", "nation_nm" => "MARSHALL ISLANDS", "capital" => "MAJURO"],
            ["nation_cd" => "7", "nation_nm" => "KAZAKHSTAN", "capital" => "ASTANA"],
            ["nation_cd" => "708", "nation_nm" => "TAJIKISTAN", "capital" => "DUSHANBE"],
            ["nation_cd" => "709", "nation_nm" => "TURKMENISTAN", "capital" => "ASHGABAT"],
            ["nation_cd" => "71", "nation_nm" => "KYRGYZSTAN", "capital" => "BISHKEK"],
            ["nation_cd" => "711", "nation_nm" => "UZBEKISTAN", "capital" => "TASHKENT"],
            ["nation_cd" => "72", "nation_nm" => "RUSSIA", "capital" => "MOSCOW"],
            ["nation_cd" => "81", "nation_nm" => "JAPAN", "capital" => "TOKYO"],
            ["nation_cd" => "82", "nation_nm" => "KOREA, SOUTH", "capital" => "SEOUL"],
            ["nation_cd" => "84", "nation_nm" => "VIETNAM", "capital" => "HANOI"],
            ["nation_cd" => "850", "nation_nm" => "KOREA, NORTH", "capital" => "PYONGYANG"],
            ["nation_cd" => "852", "nation_nm" => "HONG KONG", "capital" => "HONG KONG"],
            ["nation_cd" => "855", "nation_nm" => "CAMBODIA", "capital" => "PHNOM PENH"],
            ["nation_cd" => "856", "nation_nm" => "LAOS", "capital" => "VIENTIANE"],
            ["nation_cd" => "86", "nation_nm" => "CHINA", "capital" => "BEIJING"],
            ["nation_cd" => "880", "nation_nm" => "BANGLADESH", "capital" => "DHAKA"],
            ["nation_cd" => "886", "nation_nm" => "TAIWAN", "capital" => "TAIPEI"],
            ["nation_cd" => "90", "nation_nm" => "TURKEY", "capital" => "ANKARA"],
            ["nation_cd" => "91", "nation_nm" => "INDIA", "capital" => "NEW DELHI"],
            ["nation_cd" => "92", "nation_nm" => "PAKISTAN", "capital" => "ISLAMABAD"],
            ["nation_cd" => "93", "nation_nm" => "AFGHANISTAN", "capital" => "KABUL"],
            ["nation_cd" => "94", "nation_nm" => "SRI LANKA", "capital" => "SRI JAYAWARDENEPURA KOTTE"],
            ["nation_cd" => "95", "nation_nm" => "MYANMAR", "capital" => "RANGOON"],
            ["nation_cd" => "960", "nation_nm" => "MALDIVES", "capital" => "MALE"],
            ["nation_cd" => "961", "nation_nm" => "LEBANON", "capital" => "BEIRUT"],
            ["nation_cd" => "962", "nation_nm" => "JORDAN", "capital" => "AMMAN"],
            ["nation_cd" => "963", "nation_nm" => "SYRIAN ARAB REP.", "capital" => "DAMASCUS"],
            ["nation_cd" => "964", "nation_nm" => "IRAQ", "capital" => "BAGHDAD"],
            ["nation_cd" => "965", "nation_nm" => "KUWAIT", "capital" => "KUWAIT CITY"],
            ["nation_cd" => "966", "nation_nm" => "SAUDI ARABIA", "capital" => "RIYADH"],
            ["nation_cd" => "967", "nation_nm" => "YEMEN", "capital" => "SANA"],
            ["nation_cd" => "968", "nation_nm" => "OMAN", "capital" => "MUSCAT"],
            ["nation_cd" => "971", "nation_nm" => "UNITED ARAB EMIRATES", "capital" => "ABU DHABI"],
            ["nation_cd" => "972", "nation_nm" => "ISRAEL", "capital" => "JERUSALEM"],
            ["nation_cd" => "973", "nation_nm" => "BAHRAIN", "capital" => "MANAMA"],
            ["nation_cd" => "974", "nation_nm" => "QATAR", "capital" => "DOHA"],
            ["nation_cd" => "975", "nation_nm" => "BHUTAN", "capital" => "THIMPHU"],
            ["nation_cd" => "976", "nation_nm" => "MONGOLIA", "capital" => "ULAN BATOR"],
            ["nation_cd" => "977", "nation_nm" => "NEPAL", "capital" => "KATHMANDU"],
            ["nation_cd" => "98", "nation_nm" => "IRAN, ISLAMIC REP. OF", "capital" => "TEHERAN"],
            ["nation_cd" => "994", "nation_nm" => "AZERBAIJAN", "capital" => "BAKU"],
            ["nation_cd" => "995", "nation_nm" => "GEORGIA", "capital" => "TBILISI"],
        ];

        foreach ($data as $item){
            ComNation::create($item);
        }
    }
}
