<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TrxDokterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('trx_dokter')->delete();
        
        \DB::table('trx_dokter')->insert(array (
            0 => 
            array (
                'dr_cd' => 'DR0001',
                'dr_nm' => 'dr. AHMAD AFANDI',
                'spesialis_cd' => NULL,
                'paramedis_st' => NULL,
                'nip' => NULL,
                'dr_tp' => NULL,
                'address' => NULL,
                'region_prop' => NULL,
                'region_kab' => NULL,
                'region_kec' => NULL,
                'region_kel' => NULL,
                'postcode' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'fax' => NULL,
                'email' => NULL,
                'birth_place' => NULL,
                'birth_date' => NULL,
                'age' => NULL,
                'blood_tp' => NULL,
                'weight' => NULL,
                'height' => NULL,
                'gender_tp' => NULL,
                'marital_tp' => NULL,
                'nation_cd' => NULL,
                'religion_cd' => NULL,
                'occupation_cd' => NULL,
                'education_cd' => NULL,
                'race_cd' => NULL,
                'file_picture' => NULL,
                'modi_id' => 'hexsys',
                'paramedis_tp' => 'PARAMEDIS_TP_01',
                'data_mapcd' => NULL,
            ),
            1 => 
            array (
                'dr_cd' => 'DR0002',
                'dr_nm' => 'dr. BUDI SETIAWAN',
                'spesialis_cd' => NULL,
                'paramedis_st' => NULL,
                'nip' => NULL,
                'dr_tp' => NULL,
                'address' => NULL,
                'region_prop' => NULL,
                'region_kab' => NULL,
                'region_kec' => NULL,
                'region_kel' => NULL,
                'postcode' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'fax' => NULL,
                'email' => NULL,
                'birth_place' => NULL,
                'birth_date' => NULL,
                'age' => NULL,
                'blood_tp' => NULL,
                'weight' => NULL,
                'height' => NULL,
                'gender_tp' => NULL,
                'marital_tp' => NULL,
                'nation_cd' => NULL,
                'religion_cd' => NULL,
                'occupation_cd' => NULL,
                'education_cd' => NULL,
                'race_cd' => NULL,
                'file_picture' => NULL,
                'modi_id' => 'hexsys',
                'paramedis_tp' => 'PARAMEDIS_TP_01',
                'data_mapcd' => NULL,
            ),
            2 => 
            array (
                'dr_cd' => 'TIMDOKTER',
                'dr_nm' => 'TIM DOKTER',
                'spesialis_cd' => NULL,
                'paramedis_st' => NULL,
                'nip' => NULL,
                'dr_tp' => NULL,
                'address' => NULL,
                'region_prop' => NULL,
                'region_kab' => NULL,
                'region_kec' => NULL,
                'region_kel' => NULL,
                'postcode' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'fax' => NULL,
                'email' => NULL,
                'birth_place' => NULL,
                'birth_date' => NULL,
                'age' => NULL,
                'blood_tp' => NULL,
                'weight' => NULL,
                'height' => NULL,
                'gender_tp' => NULL,
                'marital_tp' => NULL,
                'nation_cd' => NULL,
                'religion_cd' => NULL,
                'occupation_cd' => NULL,
                'education_cd' => NULL,
                'race_cd' => NULL,
                'file_picture' => NULL,
                'modi_id' => 'hexsys',
                'paramedis_tp' => 'PARAMEDIS_TP_01',
                'data_mapcd' => NULL,
            ),
            3 => 
            array (
                'dr_cd' => 'DR0003',
                'dr_nm' => 'dr. CICI SUSANTI',
                'spesialis_cd' => NULL,
                'paramedis_st' => NULL,
                'nip' => NULL,
                'dr_tp' => NULL,
                'address' => NULL,
                'region_prop' => NULL,
                'region_kab' => NULL,
                'region_kec' => NULL,
                'region_kel' => NULL,
                'postcode' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'fax' => NULL,
                'email' => NULL,
                'birth_place' => NULL,
                'birth_date' => NULL,
                'age' => NULL,
                'blood_tp' => NULL,
                'weight' => NULL,
                'height' => NULL,
                'gender_tp' => NULL,
                'marital_tp' => NULL,
                'nation_cd' => NULL,
                'religion_cd' => NULL,
                'occupation_cd' => NULL,
                'education_cd' => NULL,
                'race_cd' => NULL,
                'file_picture' => NULL,
                'modi_id' => 'hexsys',
                'paramedis_tp' => 'PARAMEDIS_TP_01',
                'data_mapcd' => NULL,
            ),
            4 => 
            array (
                'dr_cd' => 'DR0004',
                'dr_nm' => 'dr. ANDI BASKOSO Sp.A',
                'spesialis_cd' => NULL,
                'paramedis_st' => NULL,
                'nip' => NULL,
                'dr_tp' => NULL,
                'address' => NULL,
                'region_prop' => NULL,
                'region_kab' => NULL,
                'region_kec' => NULL,
                'region_kel' => NULL,
                'postcode' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'fax' => NULL,
                'email' => NULL,
                'birth_place' => NULL,
                'birth_date' => NULL,
                'age' => NULL,
                'blood_tp' => NULL,
                'weight' => NULL,
                'height' => NULL,
                'gender_tp' => NULL,
                'marital_tp' => NULL,
                'nation_cd' => NULL,
                'religion_cd' => NULL,
                'occupation_cd' => NULL,
                'education_cd' => NULL,
                'race_cd' => NULL,
                'file_picture' => NULL,
                'modi_id' => 'hexsys',
                'paramedis_tp' => 'PARAMEDIS_TP_02',
                'data_mapcd' => NULL,
            ),
            5 => 
            array (
                'dr_cd' => 'DR0005',
                'dr_nm' => 'dr. BASUKI PRAMONO, Sp.Pd',
                'spesialis_cd' => NULL,
                'paramedis_st' => NULL,
                'nip' => NULL,
                'dr_tp' => NULL,
                'address' => NULL,
                'region_prop' => NULL,
                'region_kab' => NULL,
                'region_kec' => NULL,
                'region_kel' => NULL,
                'postcode' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'fax' => NULL,
                'email' => NULL,
                'birth_place' => NULL,
                'birth_date' => NULL,
                'age' => NULL,
                'blood_tp' => NULL,
                'weight' => NULL,
                'height' => NULL,
                'gender_tp' => NULL,
                'marital_tp' => NULL,
                'nation_cd' => NULL,
                'religion_cd' => NULL,
                'occupation_cd' => NULL,
                'education_cd' => NULL,
                'race_cd' => NULL,
                'file_picture' => NULL,
                'modi_id' => 'hexsys',
                'paramedis_tp' => 'PARAMEDIS_TP_02',
                'data_mapcd' => NULL,
            ),
        ));

        
    }
}